[task_local]
0 0 * * * https://raw.githubusercontent.com/ruiqicwbjzx/qx/main/bitboo_quantumultx_decrypt.js, tag=BitBoo, enabled=true, argument=mode=task&secret=bitboo8888oobtib

[rewrite_local]
^https:\/\/81\.71\.98\.184\/api_v2\/node_list url script-response-body https://raw.githubusercontent.com/ruiqicwbjzx/qx/main/bitboo_quantumultx_decrypt.js

[mitm]
hostname = 81.71.98.184
